-- =============================================================================
-- 04_grants.sql
-- SBI Canada — Attribution des permissions par rôle fonctionnel
-- Prérequis : avoir exécuté 00_variables.sql dans la même session
-- =============================================================================

USE ROLE SYSADMIN;

-- =============================================================================
-- ADMIN_ROLE : accès complet à tout
-- =============================================================================
GRANT ALL ON DATABASE IDENTIFIER($DEMO_DB)     TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT ALL ON DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT ALL ON DATABASE IDENTIFIER($PROJECTS_DB) TO ROLE IDENTIFIER($ADMIN_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($ADMIN_WH)    TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($DEMO_WH)     TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($TRAINING_WH) TO ROLE IDENTIFIER($ADMIN_ROLE);

-- =============================================================================
-- DEMO_ROLE : DEMO_DB et DEMO_WH uniquement
-- =============================================================================
GRANT USAGE ON DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($DEMO_WH)
  TO ROLE IDENTIFIER($DEMO_ROLE);

-- =============================================================================
-- TRAINING_ROLE : TRAINING_DB et TRAINING_WH uniquement
-- =============================================================================
GRANT USAGE ON DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($TRAINING_WH)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

-- =============================================================================
-- PROJECTS_DB : à compléter lors du premier projet client
-- =============================================================================
-- USE DATABASE IDENTIFIER($PROJECTS_DB);
-- CREATE SCHEMA IF NOT EXISTS <NOM_PROJET>_SCH;
-- GRANT USAGE ON DATABASE IDENTIFIER($PROJECTS_DB) TO ROLE <ROLE_PROJET>;
-- GRANT USAGE ON SCHEMA <NOM_PROJET>_SCH           TO ROLE <ROLE_PROJET>;

-- Vérification
SHOW GRANTS TO ROLE IDENTIFIER($DEMO_ROLE);
SHOW GRANTS TO ROLE IDENTIFIER($TRAINING_ROLE);
SHOW GRANTS TO ROLE IDENTIFIER($ADMIN_ROLE);
