-- =============================================================================
-- 04_grants.sql
-- SBI Canada — Attribution des permissions par rôle fonctionnel
-- Prérequis : avoir exécuté 00_variables.sql dans la même session
-- =============================================================================
-- Architecture des accès :
--   ADMIN_ROLE    → accès complet à toutes les bases + tous les warehouses
--   DEMO_ROLE     → accès complet à DEMO_DB + DEMO_WH
--                   (création de tables, vues, stages, pipes, etc.)
--   TRAINING_ROLE → accès complet à TRAINING_DB + TRAINING_WH
--                   (création de tables, vues, stages, pipes, etc.)
-- =============================================================================

USE ROLE SYSADMIN;

-- =============================================================================
-- ADMIN_ROLE : accès complet à tout
-- =============================================================================
GRANT ALL ON DATABASE IDENTIFIER($DEMO_DB)     TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT ALL ON DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT ALL ON DATABASE IDENTIFIER($PROJECTS_DB) TO ROLE IDENTIFIER($ADMIN_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($ADMIN_WH)    TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($DEMO_WH)     TO ROLE IDENTIFIER($ADMIN_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($TRAINING_WH) TO ROLE IDENTIFIER($ADMIN_ROLE);

-- =============================================================================
-- DEMO_ROLE : accès complet à DEMO_DB + DEMO_WH
-- CREATE SCHEMA, TABLE, VIEW, STAGE, PIPE, STREAM, TASK, FILE FORMAT...
-- =============================================================================

-- Niveau base de données (inclut CREATE SCHEMA)
GRANT ALL ON DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

-- Niveau schemas existants (inclut CREATE TABLE, VIEW, STAGE, PIPE, etc.)
GRANT ALL ON ALL SCHEMAS IN DATABASE IDENTIFIER($DEMO_DB)
  TO ROLE IDENTIFIER($DEMO_ROLE);

-- Niveau objets existants
GRANT ALL ON ALL TABLES  IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON ALL VIEWS   IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON ALL STAGES  IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON ALL PIPES   IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON ALL STREAMS IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON ALL TASKS   IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);

-- Future grants : tout nouvel objet créé dans DEMO_DB sera automatiquement accessible
GRANT ALL ON FUTURE SCHEMAS  IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE TABLES   IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE VIEWS    IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE STAGES   IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE PIPES    IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE STREAMS  IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);
GRANT ALL ON FUTURE TASKS    IN DATABASE IDENTIFIER($DEMO_DB) TO ROLE IDENTIFIER($DEMO_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($DEMO_WH) TO ROLE IDENTIFIER($DEMO_ROLE);

-- =============================================================================
-- TRAINING_ROLE : accès complet à TRAINING_DB + TRAINING_WH
-- CREATE SCHEMA, TABLE, VIEW, STAGE, PIPE, STREAM, TASK, FILE FORMAT...
-- =============================================================================

-- Niveau base de données (inclut CREATE SCHEMA)
GRANT ALL ON DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

-- Niveau schemas existants
GRANT ALL ON ALL SCHEMAS IN DATABASE IDENTIFIER($TRAINING_DB)
  TO ROLE IDENTIFIER($TRAINING_ROLE);

-- Niveau objets existants
GRANT ALL ON ALL TABLES  IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON ALL VIEWS   IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON ALL STAGES  IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON ALL PIPES   IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON ALL STREAMS IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON ALL TASKS   IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);

-- Future grants
GRANT ALL ON FUTURE SCHEMAS  IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE TABLES   IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE VIEWS    IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE STAGES   IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE PIPES    IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE STREAMS  IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);
GRANT ALL ON FUTURE TASKS    IN DATABASE IDENTIFIER($TRAINING_DB) TO ROLE IDENTIFIER($TRAINING_ROLE);

GRANT USAGE ON WAREHOUSE IDENTIFIER($TRAINING_WH) TO ROLE IDENTIFIER($TRAINING_ROLE);

-- =============================================================================
-- PROJECTS_DB : à compléter lors du premier projet client
-- =============================================================================
-- GRANT ALL ON DATABASE IDENTIFIER($PROJECTS_DB) TO ROLE <ROLE_PROJET>;

-- =============================================================================
-- Vérification
-- =============================================================================
SHOW GRANTS TO ROLE IDENTIFIER($ADMIN_ROLE);
SHOW GRANTS TO ROLE IDENTIFIER($DEMO_ROLE);
SHOW GRANTS TO ROLE IDENTIFIER($TRAINING_ROLE);
